### ISSUE TITLE
Uninhibited Phase 2: Reports Development EPIC

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#102]
```[tasklist]
### Tasks
- [ ] https://github.com/avniproject/uninhibited/issues/98
- [ ] https://github.com/avniproject/uninhibited/issues/77
- [ ] https://github.com/avniproject/uninhibited/issues/97
- [ ] https://github.com/avniproject/uninhibited/issues/94
- [ ] https://github.com/avniproject/uninhibited/issues/90
- [ ] https://github.com/avniproject/uninhibited/issues/89
- [ ] https://github.com/avniproject/uninhibited/issues/85
- [ ] https://github.com/avniproject/uninhibited/issues/92
- [ ] https://github.com/avniproject/uninhibited/issues/86
- [ ] https://github.com/avniproject/uninhibited/issues/79
- [ ] https://github.com/avniproject/uninhibited/issues/80
- [ ] https://github.com/avniproject/uninhibited/issues/82
- [ ] https://github.com/avniproject/uninhibited/issues/81
- [ ] https://github.com/avniproject/uninhibited/issues/83
- [ ] https://github.com/avniproject/uninhibited/issues/78
- [ ] https://github.com/avniproject/uninhibited/issues/88
- [ ] https://github.com/avniproject/uninhibited/issues/87
- [ ] https://github.com/avniproject/uninhibited/issues/93
- [ ] https://github.com/avniproject/uninhibited/issues/96
- [ ] https://github.com/avniproject/uninhibited/issues/91
- [ ] https://github.com/avniproject/uninhibited/issues/95
- [ ] https://github.com/avniproject/uninhibited/issues/100
- [ ] https://github.com/avniproject/uninhibited/issues/101
- [ ] https://github.com/avniproject/uninhibited/issues/73
- [ ] https://github.com/avniproject/uninhibited/issues/71
- [ ] https://github.com/avniproject/uninhibited/issues/56
```
