### ISSUE TITLE
Uninhibited Phase 2: App: Go Live & Warrenty

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/uninhibited#32]
Functional

- [x] App Flow
- [x] Visit Scheduling Logic: All Forms
- [x] User Group Permissions
- [ ] Operational Dashboard Cards

Data

- [x]  Users, Location & Catchment Data & Creation
- [ ]  Void all test data in production
- [ ]  Disable UAT users
