### ISSUE TITLE
Uninhibited Phase 2: Offline Dashboard: Period Tracking

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#43]
- [x] To be done in UAT first.
- [x] [Link](https://docs.google.com/spreadsheets/d/186H_Wv4LS08qKjQBFxKmINe9izSEPyJZdKQrlnRghac/edit?gid=1788298836#gid=1788298836)
- [ ] To be enabled only for Fellows and Admin.

### Tech notes
We can use Standard cards for this.
