### ISSUE TITLE
Uninhibited Phase 2: Checklist for BA & QA.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#44]
- [ ]  Visit Schedule Logics
- [ ]  Over all App flow
- [ ]  User Group Permissions
- [ ]  Translations
- [ ]  Disable UAT Users
