### ISSUE TITLE
Uninhibited Phase 2: PS 4.1 Period Tracking Program

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#62]
- [x] Create a program named "PS 4.1 Period Tracking Program" in UAT.
- [x] Map the encounter "Period Tracking" to "PS 4.1 Period Tracking Program.".
- [x] "PS 4.1 Period Tracking Program" is an empty form.
- [x] Remove the visit schedule logic of Period Tracking from the registration form and add in "PS 4.1 Period Tracking Program" enrolment.

**Comment by Dinesh2019** [comment]
- [ ] Add the check to avoid the unplanned visit

**Comment by Dinesh2019** [comment]
Refer QA video : 


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWNGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d793527af31c0e7a341aec28700c7f0273cfaa7/My%20Movie.mp4
