### ISSUE TITLE
Period Tracking: 5. Percentage of bleeding pattern during the most recent menstrual cycle

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#81]
- [x]  Report to be made in UAT and in Metabase.
- [x]  [Analysis Link](https://docs.google.com/spreadsheets/d/15gmlRxBRIuXRY5X_GHNkHxtXNFefkdelR-sPTLjYORE/edit?gid=2004938207#gid=2004938207&range=91:115)

**Comment by adamsanadi6** [comment]
Dashboard link: [Period Tracking](https://reporting.avniproject.org/dashboard/322)

**Comment by sachsk** [comment]
Code review comment: Report query appears to be incorrect. It should display the total number of registered individuals for the percentage calculation, but it currently uses an inner join for enrollment, which only includes individuals who are enrolled in the program.

**Comment by Dinesh2019** [comment]
QA Reference video : 

[Click here to watch video](https://drive.google.com/file/d/1Rt4lYvNBj0yLTjmvcgQ8hNu466amSZ_K/view?usp=drive_link)

**Comment by Dinesh2019** [comment]
- [ ] Are we going to add the count of exited count

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal and @kameshbhariya, I have replaced the ‘Out of Range’ filter option with ‘Below 12 & Above 19’ in the Age Category column as well as in the Age Category filter.
