### ISSUE TITLE
Period Tracking: 7. Percentage of Length of the most recent menstrual cycle

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#83]
- [x]  Report to be made in UAT and in Metabase.
- [x]  [Analysis Link](https://docs.google.com/spreadsheets/d/15gmlRxBRIuXRY5X_GHNkHxtXNFefkdelR-sPTLjYORE/edit?gid=2004938207#gid=2004938207&range=148:166)

**Comment by adamsanadi6** [comment]
Dashboard link: [Period Tracking](https://reporting.avniproject.org/dashboard/322)

**Comment by sachsk** [comment]
Code review comment: Report query appears to be incorrect. It should consider  the total number of registered individuals for percentage, but it currently uses an inner join for enrollment, which only includes individuals who are enrolled in the program.

**Comment by Dinesh2019** [comment]
For the dashboard if we remove the filter at a time then we have the count mismatch 

Reference image : 

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGNDQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e15cb2e84ba5701ebf7fa0f2a08b0f7e4f375d9a/Screenshot%202024-09-26%20at%201.02.48%E2%80%AFPM.png" alt="Screenshot 2024-09-26 at 1.02.48 PM.png" />

**Comment by Dinesh2019** [comment]
- [ ] We have the metabase issue which is not reproduced.

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal and @kameshbhariya, I have replaced the ‘Out of Range’ filter option with ‘Below 12 & Above 19’ in the Age Category column as well as in the Age Category filter.
