### ISSUE TITLE
Uninhibited Phase 2: Percentage of girls who started tracking post the sessions

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#92]
- [x] Reports to be made in UAT and in Metabase.
- [x] [Analysis Link](https://docs.google.com/spreadsheets/d/15gmlRxBRIuXRY5X_GHNkHxtXNFefkdelR-sPTLjYORE/edit?gid=637888797#gid=637888797)
- [x] Description: This report shows the percentage and details of girls who began tracking their menstrual cycles after participating in educational sessions, demonstrating the impact of these sessions on their awareness and behavior.

**Comment by manish-sd** [comment]
[DashBoard Link](https://reporting.avniproject.org/dashboard/324-pre-and-post-programme-comparative)

**Comment by manish-sd** [comment]
[Report Collection](https://reporting.avniproject.org/collection/770-girls-who-started-tracking-post-the-sessions)

**Comment by adamsanadi6** [comment]
[Dashboard link](https://reporting.avniproject.org/dashboard/326)

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal and @kameshbhariya, I have replaced the ‘Out of Range’ filter option with ‘Below 12 & Above 19’ in the Age Category column as well as in the Age Category filter.

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal 
**Changes made:**
1. Removed unnecessary joins (duplicate records were appearing in the result).
2. Updated the aggregate report condition (used the ‘contains’ method instead of ‘equals,’ as it’s a multiselect question).

**Comment by nupoorkhandelwal** [comment]
@adamsanadi6 graph is not loading, please check [Uploading... Screenshot 2024-10-24 at 11.44.00 AM.png]
